name: Build and Test

on: [push, pull_request,workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest",'windows-latest','macos-latest']
        python-version: [3.8, 3.9, "3.10.6"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - if: runner.os == 'Windows'
        run: |
             # This is not bash but a placeholder from WSL that tells you to install some WSL crap
             # and by doing so it shadows the actual bash executable when calling CreateProcess from
             # winapi, which rust's std::Command does ...
             rm 'C:\Windows\System32\bash.exe'
      - name: setup
        run: |
            python -m pip install -U pip wheel setuptools
            mkdir pact
            make setup
            make install
            make grpc_install
      - run: make run_hello_ffi
      - run: make test

  act:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup
        run: |
            python -m pip install -U pip wheel setuptools
            mkdir pact
            make setup
            make install
            make grpc_install
      - run: make run_hello_ffi
      - run: make test